name: Blog Post Workflow 2025 Master

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      product:
        description: 'Affiliate product to research'
        required: false
        default: 'Wrap Him Around Your Finger'
      persona:
        description: 'Target persona label'
        required: false
        default: 'Heart-Led High Achiever'
      lookback_days:
        description: 'Recency window for trend data'
        required: false
        default: '30'

permissions:
  contents: read

concurrency:
  group: blog-master-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stage1_research:
    name: Stage 1 — Research & Strategy
    runs-on: ubuntu-latest
    outputs:
      product: ${{ steps.resolve_inputs.outputs.product }}
      persona: ${{ steps.resolve_inputs.outputs.persona }}
      lookback_days: ${{ steps.resolve_inputs.outputs.lookback_days }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Resolve workflow inputs
        id: resolve_inputs
        run: |
          python3 <<'PY'
          import json
          import os

          defaults = {
              "product": "Wrap Him Around Your Finger",
              "persona": "Heart-Led High Achiever",
              "lookback_days": "30",
          }

          event_path = os.environ.get("GITHUB_EVENT_PATH")
          data = {}
          if event_path and os.path.exists(event_path):
              with open(event_path, "r", encoding="utf-8") as handle:
                  data = json.load(handle)

          inputs = (data.get("inputs") or {})
          client_payload = (data.get("client_payload") or {})

          product = inputs.get("product") or client_payload.get("product") or defaults["product"]
          persona = inputs.get("persona") or client_payload.get("persona") or defaults["persona"]
          lookback_days = inputs.get("lookback_days") or client_payload.get("lookback_days") or defaults["lookback_days"]

          output_path = os.environ["GITHUB_OUTPUT"]
          with open(output_path, "w", encoding="utf-8") as fh:
              fh.write(f"product={product}\n")
              fh.write(f"persona={persona}\n")
              fh.write(f"lookback_days={lookback_days}\n")
          PY

      - name: Export runtime configuration
        run: |
          {
            echo "PRODUCT=${{ steps.resolve_inputs.outputs.product }}"
            echo "PERSONA_NAME=${{ steps.resolve_inputs.outputs.persona }}"
            echo "LOOKBACK_DAYS=${{ steps.resolve_inputs.outputs.lookback_days }}"
          } >> "$GITHUB_ENV"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install workflow dependencies
        run: pip install -r requirements.txt

      - name: Generate Stage 1 research artifacts
        run: |
          python scripts/python/generate_stage_artifacts.py stage1 \
            --output-dir artifacts/stage1 \
            --product "${PRODUCT}" \
            --persona-name "${PERSONA_NAME}" \
            --lookback-days "${LOOKBACK_DAYS}"

      - name: Upload Stage 1 artifact bundle
        uses: actions/upload-artifact@v4
        with:
          name: stage1-research
          path: artifacts/stage1

  stage2_creation:
    name: Stage 2 — Blog Creation & Optimization
    needs: stage1_research
    runs-on: ubuntu-latest
    outputs:
      product: ${{ steps.forward_configuration.outputs.product }}
      persona: ${{ steps.forward_configuration.outputs.persona }}
      lookback_days: ${{ steps.forward_configuration.outputs.lookback_days }}
    env:
      PRODUCT: ${{ needs.stage1_research.outputs.product }}
      PERSONA_NAME: ${{ needs.stage1_research.outputs.persona }}
      LOOKBACK_DAYS: ${{ needs.stage1_research.outputs.lookback_days }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install workflow dependencies
        run: pip install -r requirements.txt

      - name: Retrieve Stage 1 research bundle
        uses: actions/download-artifact@v4
        with:
          name: stage1-research
          path: artifacts/stage1

      - name: Generate Stage 2 creation artifacts
        run: |
          python scripts/python/generate_stage_artifacts.py stage2 \
            --output-dir artifacts/stage2 \
            --context artifacts/stage1/context.json \
            --product "${PRODUCT}" \
            --persona-name "${PERSONA_NAME}" \
            --lookback-days "${LOOKBACK_DAYS}"

      - name: Forward configuration for downstream stages
        id: forward_configuration
        run: |
          {
            printf 'product=%s\n' "${PRODUCT}"
            printf 'persona=%s\n' "${PERSONA_NAME}"
            printf 'lookback_days=%s\n' "${LOOKBACK_DAYS}"
          } >> "$GITHUB_OUTPUT"

      - name: Upload Stage 2 artifact bundle
        uses: actions/upload-artifact@v4
        with:
          name: stage2-creation
          path: artifacts/stage2

  stage3_distribution:
    name: Stage 3 — Cross-Platform Distribution
    needs: stage2_creation
    runs-on: ubuntu-latest
    outputs:
      product: ${{ steps.forward_configuration.outputs.product }}
      persona: ${{ steps.forward_configuration.outputs.persona }}
      lookback_days: ${{ steps.forward_configuration.outputs.lookback_days }}
    env:
      PRODUCT: ${{ needs.stage2_creation.outputs.product }}
      PERSONA_NAME: ${{ needs.stage2_creation.outputs.persona }}
      LOOKBACK_DAYS: ${{ needs.stage2_creation.outputs.lookback_days }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install workflow dependencies
        run: pip install -r requirements.txt

      - name: Retrieve Stage 2 bundle
        uses: actions/download-artifact@v4
        with:
          name: stage2-creation
          path: artifacts/stage2

      - name: Generate Stage 3 distribution artifacts
        run: |
          python scripts/python/generate_stage_artifacts.py stage3 \
            --output-dir artifacts/stage3 \
            --context artifacts/stage2/context.json \
            --product "${PRODUCT}" \
            --persona-name "${PERSONA_NAME}" \
            --lookback-days "${LOOKBACK_DAYS}"

      - name: Forward configuration for downstream stages
        id: forward_configuration
        run: |
          {
            printf 'product=%s\n' "${PRODUCT}"
            printf 'persona=%s\n' "${PERSONA_NAME}"
            printf 'lookback_days=%s\n' "${LOOKBACK_DAYS}"
          } >> "$GITHUB_OUTPUT"

      - name: Upload Stage 3 artifact bundle
        uses: actions/upload-artifact@v4
        with:
          name: stage3-distribution
          path: artifacts/stage3

  stage4_analytics:
    name: Stage 4 — Analytics & Refinement
    needs: stage3_distribution
    runs-on: ubuntu-latest
    outputs:
      product: ${{ steps.forward_configuration.outputs.product }}
      persona: ${{ steps.forward_configuration.outputs.persona }}
      lookback_days: ${{ steps.forward_configuration.outputs.lookback_days }}
    env:
      PRODUCT: ${{ needs.stage3_distribution.outputs.product }}
      PERSONA_NAME: ${{ needs.stage3_distribution.outputs.persona }}
      LOOKBACK_DAYS: ${{ needs.stage3_distribution.outputs.lookback_days }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install workflow dependencies
        run: pip install -r requirements.txt

      - name: Retrieve Stage 3 bundle
        uses: actions/download-artifact@v4
        with:
          name: stage3-distribution
          path: artifacts/stage3

      - name: Generate Stage 4 analytics artifacts
        run: |
          python scripts/python/generate_stage_artifacts.py stage4 \
            --output-dir artifacts/stage4 \
            --context artifacts/stage3/context.json \
            --product "${PRODUCT}" \
            --persona-name "${PERSONA_NAME}" \
            --lookback-days "${LOOKBACK_DAYS}"

      - name: Forward configuration for downstream stages
        id: forward_configuration
        run: |
          {
            printf 'product=%s\n' "${PRODUCT}"
            printf 'persona=%s\n' "${PERSONA_NAME}"
            printf 'lookback_days=%s\n' "${LOOKBACK_DAYS}"
          } >> "$GITHUB_OUTPUT"

      - name: Upload Stage 4 artifact bundle
        uses: actions/upload-artifact@v4
        with:
          name: stage4-analytics
          path: artifacts/stage4

  stage5_growth:
    name: Stage 5 — Continuous Growth Loop
    needs: stage4_analytics
    runs-on: ubuntu-latest
    env:
      PRODUCT: ${{ needs.stage4_analytics.outputs.product }}
      PERSONA_NAME: ${{ needs.stage4_analytics.outputs.persona }}
      LOOKBACK_DAYS: ${{ needs.stage4_analytics.outputs.lookback_days }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install workflow dependencies
        run: pip install -r requirements.txt

      - name: Retrieve Stage 4 bundle
        uses: actions/download-artifact@v4
        with:
          name: stage4-analytics
          path: artifacts/stage4

      - name: Generate Stage 5 growth artifacts
        run: |
          python scripts/python/generate_stage_artifacts.py stage5 \
            --output-dir artifacts/stage5 \
            --context artifacts/stage4/context.json \
            --product "${PRODUCT}" \
            --persona-name "${PERSONA_NAME}" \
            --lookback-days "${LOOKBACK_DAYS}"

      - name: Upload Stage 5 artifact bundle
        uses: actions/upload-artifact@v4
        with:
          name: stage5-growth
          path: artifacts/stage5
