name: Stage 1 — Research & Keyword Cluster Selection (Research-Only)

on:
  workflow_dispatch:
    inputs:
      product:
        description: "Affiliate product (e.g., Wrap Him Around Your Finger)"
        required: true
        default: "Wrap Him Around Your Finger"
      persona:
        description: "Target persona (e.g., Dating & Relationship Advice for Women)"
        required: true
        default: "Dating & Relationship Advice for Women"
      lookback_days:
        description: "Recency window for trend data (e.g., 30)"
        required: false
        default: "30"

  repository_dispatch:
    types: [stage1_start, notion_brief_updated]

  push:
    branches: [ main ]
    paths:
      - ".github/workflows/stage1-research phase.yml"

permissions:
  contents: write
  actions: read
  id-token: write

concurrency:
  group: stage1-${{ github.ref }}
  cancel-in-progress: true

env:
  PRODUCT: ${{ (github.event_name == 'workflow_dispatch' && inputs.product) || (github.event_name == 'repository_dispatch' && github.event.client_payload.product) || 'Wrap Him Around Your Finger' }}
  PERSONA_NAME: ${{ (github.event_name == 'workflow_dispatch' && inputs.persona) || (github.event_name == 'repository_dispatch' && github.event.client_payload.persona) || 'Dating & Relationship Advice for Women' }}
  LOOKBACK_DAYS: ${{ (github.event_name == 'workflow_dispatch' && inputs.lookback_days) || (github.event_name == 'repository_dispatch' && github.event.client_payload.lookback_days) || '30' }}

jobs:
  research:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install workflow dependencies
        run: pip install -r requirements.txt

      - name: Generate Stage 1 research artifacts
        run: |
          python scripts/python/generate_stage_artifacts.py stage1 \
            --output-dir artifacts/stage1 \
            --product "${PRODUCT}" \
            --persona-name "${PERSONA_NAME}" \
            --lookback-days "${LOOKBACK_DAYS}"

      - name: Upload Stage 1 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stage1-research
          path: artifacts/stage1/
