name: Stage 1 — Research & Keyword Cluster Selection (Research-Only)

on:
  workflow_dispatch:
    inputs:
      product:
        description: "Affiliate product (e.g., Wrap Him Around Your Finger)"
        required: true
        default: "Wrap Him Around Your Finger"
      persona:
        description: "Target persona (e.g., Dating & Relationship Advice for Women)"
        required: true
        default: "Dating & Relationship Advice for Women"
      lookback_days:
        description: "Recency window for trend data (e.g., 30)"
        required: false
        default: "30"

  repository_dispatch:
    types: [stage1_start, notion_brief_updated]

  push:
    branches: [ main ]
    paths:
      - "research/**"
      - "scripts/research/**"
      - ".github/workflows/stage1-research.yml"

permissions:
  contents: write
  actions: read
  id-token: write

concurrency:
  group: stage1-${{ github.ref }}
  cancel-in-progress: true

env:
  PRODUCT: ${{ inputs.product || github.event.client_payload.product || 'Wrap Him Around Your Finger' }}
  PERSONA: ${{ inputs.persona || github.event.client_payload.persona || 'Dating & Relationship Advice for Women' }}
  LOOKBACK_DAYS: ${{ inputs.lookback_days || github.event.client_payload.lookback_days || '30' }}

jobs:
  research:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json

      - name: Install dependencies (with lockfile)
        if: ${{ hashFiles('**/package-lock.json') != '' }}
        run: npm ci

      - name: Install dependencies (without lockfile)
        if: ${{ hashFiles('**/package-lock.json') == '' }}
        run: npm install

      - name: Gather cross-platform keyword candidates
        run: npm run research:gather --if-present

      - name: Build keyword clusters
        run: npm run research:cluster --if-present

      - name: Auto-select best cluster with justification
        run: npm run research:autoselect --if-present

      - name: Create Accelerator SEO package
        run: npm run research:seo:package --if-present

      - name: Generate title seeds + hooks for Stage 2/3
        run: npm run research:seeds --if-present

      - name: Persist artifacts
        run: |
          mkdir -p artifacts/stage1
          cp -r research/output/* artifacts/stage1/ || true

      - name: Upload Stage 1 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stage1-research
          path: artifacts/stage1/
